    version: 0.2
          
    phases:
      install:
        commands:
          - pwd
          - ls
          - cd ../
          - pwd
          - ls
          - cd ../   
          - pwd
          - ls
          - cd ../  
          - pwd
          - ls
          - cd ../    
          - pwd
          - ls
          - cd ../    
          - pwd
          - ls
          - cd ../
            
      pre_build:
        commands:
          - export PYTHONPATH=.
          - pylint ssm.py|| exit 0

          
      build:
        commands:
          # - command
      post_build:
        commands:


          # - command
    artifacts:
      files:
      - buildspec.yml
       
      discard-paths: No
     # base-directory: ssmParams
