    version: 0.2
          
    phases:
      install:
        commands:
          - java -version
          - sudo apt-get install
          - java -version
          - sudo apt-get install openjdk-7-jre
          - sudo apt-get install openjdk-7-jdk
            
      pre_build:
        commands:
          - export PYTHONPATH=.
          - pylint ssm.py|| exit 0

          
      build:
        commands:
          # - command
      post_build:
        commands:


          # - command
    artifacts:
      files:
      - buildspec.yml
       
      discard-paths: No
     # base-directory: ssmParams
